# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v3  # Updated to v3 to ensure compatibility with Node.js 16

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v3.12.12  # Still on v1.3.3 as no new version is available
        with:
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}
          
          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          # Name of the Heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dockerfile directory.
          dockerfile_directory: ./

          # Dockerfile name.
          dockerfile_name: Dockerfile

          # Additional options for docker build.
          docker_options: "--no-cache"

          # Select the process type (default: web).
          process_type: web
